<a href="https://colab.research.google.com/github/datacentertugaskuliah-coder/PraktekJST/blob/main/Inisialisasi_Bobot_Awal_untuk_Prediksi_Kanker_Payudara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ===============================================
# PROGRAM: Inisialisasi Bobot Awal untuk Prediksi Kanker Payudara
# DESKRIPSI: Program ini memuat dataset Wisconsin
# (Original) dari *UCI Machine Learning Repository*,
# melakukan *preprocessing*, dan menginisialisasi
# *matriks bobot* dan *bias* awal secara manual untuk
# jaringan syaraf sederhana.
# ===============================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# ---------- 1. Pemuatan Dataset (UCI) ----------
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
kolom = [
    "id", "clump_thickness", "uniformity_cell_size", "uniformity_cell_shape",
    "marginal_adhesion", "single_epithelial_size", "bare_nuclei",
    "bland_chromatin", "normal_nucleoli", "mitoses", "class"
]
df = pd.read_csv(url, names=kolom)

# ---------- 2. Pembersihan Data ----------
# Hapus baris dengan nilai '?' dalam kolom 'bare_nuclei'
df = df[df["bare_nuclei"] != "?"]
df["bare_nuclei"] = df["bare_nuclei"].astype(int)

# ---------- 3. Menentukan Fitur (X) & Target (y) ----------
X = df.iloc[:, 1:-1].values  # 9 fitur numerik
y = df["class"].replace({2:0,4:1}).values  # 0 = benign, 1 = malignant

# ---------- 4. Standarisasi Fitur ----------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ---------- 5. Membagi Data Train/Test ----------
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42, stratify=y)

# ---------- 6. Inisialisasi Bobot & Bias Awal ----------
np.random.seed(42)  # untuk reprodusibilitas
input_dim = X_train.shape[1]   # jumlah fitur input = 9
hidden_dim = 6                 # neuron lapisan tersembunyi
output_dim = 1                 # output tunggal (klasifikasi)

# Bobot menghimpun pengaruh input ke neuron tersembunyi
W1 = np.random.randn(input_dim, hidden_dim) * 0.01
b1 = np.zeros((1, hidden_dim))

# Bobot menghimpun pengaruh lapisan tersembunyi ke output
W2 = np.random.randn(hidden_dim, output_dim) * 0.01
b2 = np.zeros((1, output_dim))

# ---------- 7. Tampilkan Bobot &
print("Bobot awal lapisan tersembunyi (W1):")
print(W1)
print("\nBias awal lapisan tersembunyi (b1):")
print(b1)
print("\nBobot awal lapisan output (W2):")
print(W2)
print("\nBias awal lapisan output (b2):")
print(b2)

Bobot awal lapisan tersembunyi (W1):
[[ 0.00496714 -0.00138264  0.00647689  0.0152303  -0.00234153 -0.00234137]
 [ 0.01579213  0.00767435 -0.00469474  0.0054256  -0.00463418 -0.0046573 ]
 [ 0.00241962 -0.0191328  -0.01724918 -0.00562288 -0.01012831  0.00314247]
 [-0.00908024 -0.01412304  0.01465649 -0.00225776  0.00067528 -0.01424748]
 [-0.00544383  0.00110923 -0.01150994  0.00375698 -0.00600639 -0.00291694]
 [-0.00601707  0.01852278 -0.00013497 -0.01057711  0.00822545 -0.01220844]
 [ 0.00208864 -0.0195967  -0.01328186  0.00196861  0.00738467  0.00171368]
 [-0.00115648 -0.00301104 -0.01478522 -0.00719844 -0.00460639  0.01057122]
 [ 0.00343618 -0.0176304   0.00324084 -0.00385082 -0.00676922  0.00611676]]

Bias awal lapisan tersembunyi (b1):
[[0. 0. 0. 0. 0. 0.]]

Bobot awal lapisan output (W2):
[[ 0.01031   ]
 [ 0.0093128 ]
 [-0.00839218]
 [-0.00309212]
 [ 0.00331263]
 [ 0.00975545]]

Bias awal lapisan output (b2):
[[0.]]
